---
- name: install delorean-current repo
  become: true
  get_url:
    url: "{{ delorean_current_repo }}"
    dest: /etc/yum.repos.d/delorean.repo
    force: "{{ delorean_force|default(false) }}"

- name: install tripleo-repos
  become: true
  package:
    name: "python2-tripleo-repos"
    state: latest

- name: activate delorean repositories
  become: true
  command: >
    tripleo-repos {{ tripleo_delorean_repo }}

- name: upgrade installed packages
  become: true
  package:
    name: '*'
    state: latest

- name: install python-tripleoclient
  become: true
  package:
    name: python-tripleoclient
    state: installed
