{% if 'ovn' in neutron_mechanism_drivers -%}
{% set network_deploy_args = ovn_deploy_args -%}
{% elif 'openvswitch' in neutron_mechanism_drivers -%}
{% set network_deploy_args = ovs_deploy_args -%}
{% else -%}
{% set network_deploy_args = [] -%}
{% endif -%}

deploy_args=(
{% for arg in deploy_args + network_deploy_args %}
  {{ arg }}
{% endfor %}

  # parameters generated by create_config role
  -e ./standalone_parameters.yaml

{% for arg in deploy_args_extra|default([]) %}
  {{ arg }}
{% endfor %}
)

if [ -f ./local.yaml ]; then
  deploy_args+=(-e ./local.yaml)
fi

